version: "3"

services:
  vrising:
    image: miaulightouch/vrising-server-wine7
    # build: .
    container_name: vrising
    environment:
      - TZ=America/New_York
    volumes:
      - /docker/vrising/data:/data
      - /docker/vrising/logs:/logs
    ports:
      - 28015:28015/udp
      - 28016:28016/udp
    restart: unless-stopped