version: "3"

services:
  vrising:
    image: miaulightouch/vrising-server-wine7
    container_name: vrising
    environment:
      - TZ=America/New_York # optional
      - GAME_ID=1829350     # optional
      - GAME_PARAMS=        # optional
      - VALIDATE=true       # optional
    volumes:
      - /path/to/data:/data
      - /path/to/logs:/logs
      - /path/to/server:/vrising
    ports:
      - 9876-9877:9876-9877/udp
    restart: unless-stopped